"""refactored db to split schedule into schedule and time_slots

Revision ID: 72833d86f67a
Revises: 07e46d8c4322
Create Date: 2025-03-14 14:26:57.298664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '72833d86f67a'
down_revision: Union[str, None] = '07e46d8c4322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_slots',
    sa.Column('slot_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.schedule_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('slot_id'),
    sa.UniqueConstraint('schedule_id', 'start_time', 'end_time', name='uq_schedule_time')
    )
    op.create_table('appointment_time_slots',
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.appointment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['time_slots.slot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('slot_id', 'appointment_id')
    )
    op.add_column('schedule', sa.Column('is_working', sa.Boolean(), nullable=False))
    op.create_unique_constraint('uq_barber_date', 'schedule', ['barber_id', 'date'])
    op.drop_constraint('schedule_ibfk_1', 'schedule', type_='foreignkey')
    op.drop_constraint('schedule_ibfk_2', 'schedule', type_='foreignkey')
    op.create_foreign_key(None, 'schedule', 'barber', ['barber_id'], ['barber_id'])
    op.drop_column('schedule', 'appointment_id')
    op.drop_column('schedule', 'endTime')
    op.drop_column('schedule', 'startTime')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('startTime', mysql.TIME(), nullable=False))
    op.add_column('schedule', sa.Column('endTime', mysql.TIME(), nullable=False))
    op.add_column('schedule', sa.Column('appointment_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'schedule', type_='foreignkey')
    op.create_foreign_key('schedule_ibfk_2', 'schedule', 'barber', ['barber_id'], ['barber_id'], ondelete='CASCADE')
    op.create_foreign_key('schedule_ibfk_1', 'schedule', 'appointment', ['appointment_id'], ['appointment_id'], ondelete='CASCADE')
    op.drop_constraint('uq_barber_date', 'schedule', type_='unique')
    op.drop_column('schedule', 'is_working')
    op.drop_table('appointment_time_slots')
    op.drop_table('time_slots')
    # ### end Alembic commands ###
