"""Refactor Service Table

Revision ID: b01fc8702548
Revises: 72833d86f67a
Create Date: 2025-03-31 14:40:06.607794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import datetime

# revision identifiers, used by Alembic.
revision: str = 'b01fc8702548'
down_revision: Union[str, None] = '72833d86f67a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('schedule_ibfk_1', 'schedule', type_='foreignkey')
    op.create_foreign_key(None, 'schedule', 'barber', ['barber_id'], ['barber_id'], ondelete='CASCADE')
    op.add_column('service', sa.Column('category', sa.String(length=50), nullable=False))
    op.add_column('service', sa.Column('description', sa.String(500), nullable=False))
    op.add_column('service', sa.Column('popularity_score', sa.Integer(), nullable=False))
    op.alter_column('service', 'duration',
               existing_type=mysql.TIME(),
               type_=sa.Integer(),
               existing_nullable=False)
    
    # Define tables for inserting data
    status_enum = sa.Enum('pending', 'confirmed', 'completed', 'cancelled', name='appointment_status')

    users_table = sa.table(
        'user',
        sa.column('user_id', sa.Integer),
        sa.column('firstName', sa.String(50)),
        sa.column('lastName', sa.String(50)),
        sa.column('email', sa.String(50)),
        sa.column('password', sa.String(50)),
        sa.column('phoneNumber', sa.String(10)),
        sa.column('is_admin', sa.Boolean)
    )

    barbers_table = sa.table(
        'barber',
        sa.column('barber_id', sa.Integer),
        sa.column('user_id', sa.Integer)
    )

    appointments_table = sa.table(
        'appointment',
        sa.column('appointment_id', sa.Integer),
        sa.column('user_id', sa.Integer),
        sa.column('barber_id', sa.Integer),
        sa.column('status', status_enum)
    )

    services_table = sa.table(
        'service',
        sa.column('service_id', sa.Integer),
        sa.column('name', sa.String(50)),
        sa.column('duration', sa.Integer),
        sa.column('price', sa.Float(5, 2)),
        sa.column('category', sa.String(50)),
        sa.column('description', sa.String(500)),
        sa.column('popularity_score', sa.Integer)
    )

    appointment_services_table = sa.table(
        'appointment_service',
        sa.column('service_id', sa.Integer),
        sa.column('appointment_id', sa.Integer)
    )

    schedules_table = sa.table(
        'schedule',
        sa.column('schedule_id', sa.Integer),
        sa.column('barber_id', sa.Integer),
        sa.column('date', sa.Date),
        sa.column('is_working', sa.Boolean)
    )

    time_slots_table = sa.table(
        'time_slots',
        sa.column('slot_id', sa.Integer),
        sa.column('schedule_id', sa.Integer),
        sa.column('start_time', sa.Time),
        sa.column('end_time', sa.Time),
        sa.column('is_available', sa.Boolean)
    )

    appointment_time_slots_table = sa.table(
        'appointment_time_slots',
        sa.column('slot_id', sa.Integer),
        sa.column('appointment_id', sa.Integer)
    )

    threads_table = sa.table(
        'thread',
        sa.column('thread_id', sa.Integer),
        sa.column('receivingUser', sa.Integer),
        sa.column('sendingUser', sa.Integer)
    )

    messages_table = sa.table(
        'message',
        sa.column('message_id', sa.Integer),
        sa.column('thread_id', sa.Integer),
        sa.column('hasActiveMessage', sa.Boolean),
        sa.column('text', sa.Text),
        sa.column('timeStamp', sa.DateTime)
    )

    # Sample Data insert
    op.bulk_insert(
        users_table,
        [
            {
                "firstName": "John",
                "lastName": "Doe",
                "email": "john.doe@example.com",
                "phoneNumber": "1234567890",
                "password": "hashedpassword1",
                "is_admin": True,
            },
            {
                "firstName": "Jane",
                "lastName": "Smith",
                "email": "jane.smith@example.com",
                "password": "hashedpassword2",
                "phoneNumber": "0987654321",
                "is_admin": False
            },
            {
                "firstName": "Mike",
                "lastName": "Johnson",
                "email": "mike.johnson@example.com",
                "password": "hashedpassword3",
                "phoneNumber": "1122334455",
                "is_admin": True
            },
            {
                "firstName": "Sarah",
                "lastName": "Brown",
                "email": "sarah.brown@example.com",
                "password": "hashedpassword4",
                "phoneNumber": "6677889900",
                "is_admin": False
            }
        ]
    )

    op.bulk_insert(
        barbers_table,
        [
            {
                "user_id": 1
            },
            {
                "user_id": 3
            }
        ]
    )

    op.bulk_insert(
        services_table,
        [
            {
                "name": "Haircut",
                "duration": 30,
                "price": 20.00,
                "category": "Hair",
                "description": "A normal hair cut for a normal head.",
                "popularity_score": 99
            },
            {
                "name": "Beard Trim",
                "duration": 15,
                "price": 10.00,
                "category": "Facial Hair",
                "description": "The best way to combat the urge to use your beard as a bowl for ramen.",
                "popularity_score": 60
            },
            {
                "name": "Shave",
                "duration": 30,
                "price": 15.00,
                "category": "Facial Hair",
                "description": "Looking for that nice baby face look? We got you.",
                "popularity_score": 75
            },
            {
                "name": "Hair Coloring",
                "duration": 60,
                "price": 50.00,
                "category": "Hair",
                "description": "For when you want to go undercover.",
                "popularity_score": 40
            }
        ]
    )

    op.bulk_insert(
        appointments_table,
        [
            {
                "user_id": 2,
                "barber_id": 1,
                "status": "confirmed"
            },
            {
                "user_id": 4,
                "barber_id": 2,
                "status": "confirmed"
            }
        ]
    )

    op.bulk_insert(
        appointment_services_table,
        [
            {
                "service_id": 1,
                "appointment_id": 1
            },
            {
                "service_id": 3,
                "appointment_id": 2
            }
        ]
    )

    op.bulk_insert(
        schedules_table,
        [
            {
                "schedule_id": 1,
                "barber_id": 1,
                "date": (datetime.date.today() + datetime.timedelta(days=2)).strftime("%Y-%m-%d"),
                "is_working": True
            },
            {
                "schedule_id": 2,
                "barber_id": 2,
                "date": (datetime.date.today() + datetime.timedelta(days=2)).strftime("%Y-%m-%d"),
                "is_working": True
            }
        ]
    )

    op.bulk_insert(
        time_slots_table,
        [
            { "slot_id": 1, "schedule_id": 1, "start_time": "09:00:00", "end_time": "09:30:00", "is_available": False },
            { "slot_id": 2, "schedule_id": 1, "start_time": "09:30:00", "end_time": "10:00:00", "is_available": True },
            { "slot_id": 3, "schedule_id": 1, "start_time": "10:00:00", "end_time": "10:30:00", "is_available": True },
            { "slot_id": 4, "schedule_id": 1, "start_time": "10:30:00", "end_time": "11:00:00", "is_available": True },
            { "slot_id": 5, "schedule_id": 1, "start_time": "11:00:00", "end_time": "11:30:00", "is_available": True },
            { "slot_id": 6, "schedule_id": 1, "start_time": "11:30:00", "end_time": "12:00:00", "is_available": True },
            { "slot_id": 7, "schedule_id": 1, "start_time": "12:30:00", "end_time": "13:00:00", "is_available": True },
            { "slot_id": 8, "schedule_id": 1, "start_time": "13:00:00", "end_time": "13:30:00", "is_available": True },
            { "slot_id": 9, "schedule_id": 1, "start_time": "13:30:00", "end_time": "14:00:00", "is_available": True },
            { "slot_id": 10, "schedule_id": 1, "start_time": "14:00:00", "end_time": "14:30:00", "is_available": True },
            { "slot_id": 11, "schedule_id": 1, "start_time": "14:30:00", "end_time": "15:00:00", "is_available": True },
            { "slot_id": 12, "schedule_id": 1, "start_time": "15:00:00", "end_time": "15:30:00", "is_available": True },
            { "slot_id": 13, "schedule_id": 1, "start_time": "15:30:00", "end_time": "16:00:00", "is_available": True },
            { "slot_id": 14, "schedule_id": 1, "start_time": "16:00:00", "end_time": "16:30:00", "is_available": True },
            { "slot_id": 15, "schedule_id": 1, "start_time": "16:30:00", "end_time": "17:00:00", "is_available": True },
            { "slot_id": 16, "schedule_id": 2, "start_time": "09:00:00", "end_time": "09:30:00", "is_available": False },
            { "slot_id": 17, "schedule_id": 2, "start_time": "09:30:00", "end_time": "10:00:00", "is_available": True },
            { "slot_id": 18, "schedule_id": 2, "start_time": "10:00:00", "end_time": "10:30:00", "is_available": True },
            { "slot_id": 19, "schedule_id": 2, "start_time": "10:30:00", "end_time": "11:00:00", "is_available": True },
            { "slot_id": 20, "schedule_id": 2, "start_time": "11:00:00", "end_time": "11:30:00", "is_available": True },
            { "slot_id": 21, "schedule_id": 2, "start_time": "11:30:00", "end_time": "12:00:00", "is_available": True },
            { "slot_id": 22, "schedule_id": 2, "start_time": "12:30:00", "end_time": "13:00:00", "is_available": True },
            { "slot_id": 23, "schedule_id": 2, "start_time": "13:00:00", "end_time": "13:30:00", "is_available": True },
            { "slot_id": 24, "schedule_id": 2, "start_time": "13:30:00", "end_time": "14:00:00", "is_available": True },
            { "slot_id": 25, "schedule_id": 2, "start_time": "14:00:00", "end_time": "14:30:00", "is_available": True },
            { "slot_id": 26, "schedule_id": 2, "start_time": "14:30:00", "end_time": "15:00:00", "is_available": True },
            { "slot_id": 27, "schedule_id": 2, "start_time": "15:00:00", "end_time": "15:30:00", "is_available": True },
            { "slot_id": 28, "schedule_id": 2, "start_time": "15:30:00", "end_time": "16:00:00", "is_available": True },
            { "slot_id": 29, "schedule_id": 2, "start_time": "16:00:00", "end_time": "16:30:00", "is_available": True },
            { "slot_id": 30, "schedule_id": 2, "start_time": "16:30:00", "end_time": "17:00:00", "is_available": True }
        ]
    )

    op.bulk_insert(
        appointment_time_slots_table,
        [
            { "slot_id": 1, "appointment_id": 1 },
            { "slot_id": 16, "appointment_id": 2 }
        ]
    )

    op.bulk_insert(
        threads_table,
        [
            {
                "thread_id": 1,
                "receivingUser": 1,
                "sendingUser": 2
            },
            {
                "thread_id": 2,
                "receivingUser": 3,
                "sendingUser": 4
            }
        ]
    )

    op.bulk_insert(
        messages_table,
        [
            {
                "message_id": 1,
                "thread_id": 1,
                "hasActiveMessage": False,
                "text": "Hi John, I have a question about my upcoming appointment.",
                "timeStamp": "2025-02-16T10:00:00"
            },
            {
                "message_id": 2,
                "thread_id": 1,
                "hasActiveMessage": True,
                "text": "Hi Jane, sure. What can I help you with?",
                "timeStamp": "2025-02-16T10:05:00"
            },
            {
                "message_id": 3,
                "thread_id": 2,
                "hasActiveMessage": False,
                "text": "Hello Mike, I need to reschedule my appointment.",
                "timeStamp": "2025-02-16T11:00:00"
            },
            {
                "message_id": 4,
                "thread_id": 2,
                "hasActiveMessage": True,
                "text": "Hi Sarah, that's fine. Let me know your preferred time.",
                "timeStamp": "2025-02-16T11:10:00"
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service', 'duration',
               existing_type=sa.Integer(),
               type_=mysql.TIME(),
               existing_nullable=False)
    op.drop_column('service', 'popularity_score')
    op.drop_column('service', 'description')
    op.drop_column('service', 'category')
    op.drop_constraint(None, 'schedule', type_='foreignkey')
    op.create_foreign_key('schedule_ibfk_1', 'schedule', 'barber', ['barber_id'], ['barber_id'])
    # ### end Alembic commands ###
