"""adding date to appointment

Revision ID: b861b032e58a
Revises: 9870ac6d4cf2
Create Date: 2025-04-11 18:30:55.153060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b861b032e58a'
down_revision: Union[str, None] = '9870ac6d4cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('appointment_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'appointment_date')
    # ### end Alembic commands ###
