services:
  barber-shop-ui:
    image: node:22-alpine
    container_name: barber-shop-ui
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
    command: "npm run dev"

networks:
  barber-shop-network:
    external: true
