name: Deploy Frontend and Backend Separately

on:
  push:
    branches:
      - master

jobs:
  deploy-backend:
    if: github.event.head_commit.message != 'skip backend'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy Backend Files to EC2
        run: |
          rsync -avz --exclude='.git' -e "ssh -o StrictHostKeyChecking=no" ./barber-shop-api/ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/barbershop/barber-shop-api/

      - name: Deploy Backend
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/barbershop/barber-shop-api
            docker-compose down
            docker-compose up -d --build api
          EOF

  deploy-frontend:
    if: github.event.head_commit.message != 'skip frontend'
    runs-on: ubuntu-latest
    needs: deploy-backend

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy Frontend Files to EC2
        run: |
          rsync -avz --exclude='.git' -e "ssh -o StrictHostKeyChecking=no" ./barber-shop-ui/ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/barbershop/barber-shop-ui/

      - name: Deploy Frontend
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/barbershop/barber-shop-ui
            docker-compose down
            docker-compose up -d --build barber-shop-ui
          EOF
