name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Try SSH into EC2
        run: |
          ssh -tt -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "echo Hello from EC2"

      - name: Create .env file on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << EOF
            echo "MYSQL_USER=admin" > /home/ubuntu/barbershop/.env
            echo "MYSQL_PASSWORD=password" >> /home/ubuntu/barbershop/.env
            echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> /home/ubuntu/barbershop/.env
            echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> /home/ubuntu/barbershop/.env
            # Add any other necessary env variables...
          EOF


      - name: Copy Files to EC2
        run: |
          rsync -avz --exclude='.git' -e "ssh -o StrictHostKeyChecking=no" ./ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/barbershop/

      - name: SSH and Deploy
        run: |
          ssh -tt -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << EOF
            cd ~/barbershop
            docker-compose down
            docker-compose up -d --build
          EOF
